name: Pull Request Auto-Label

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  scope-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/labeler@b8dd2d9be0f68b860e7dae5dae7d772984eacd6d # v6
        id: labeler
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yaml
      # コメントする
      - name: Create comment file
        if: ${{ steps.labeler.outputs.all-labels[0] != null }}
        run: |
          cat  << EOF > comment.md
          ## PR Auto-Labeler
          Thanks for your contribution! The following labels have been automatically applied to this PR:
          EOF
          for label in ${{ steps.labeler.outputs.all-labels }}; do
            echo "- $label" >> comment.md
          done
      - name: Create PR comment
        if: ${{ steps.labeler.outputs.all-labels[0] != null }}
        run: |
          gh pr comment ${{ github.event.number }} --body-file comment.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
